spring:
  application:
    name: matriculas-servicio
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
      
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    
auth:
  service:
    url: http://localhost:8001 